export const stoicQuotes: any[] = [
  { "id": 1, "quote": "We suffer more in imagination than in reality.", "author": "Seneca" },
  { "id": 2, "quote": "You have power over your mind — not outside events.", "author": "Marcus Aurelius" },
  { "id": 3, "quote": "It is not what happens to you, but how you react to it that matters.", "author": "Epictetus" },
  { "id": 4, "quote": "The happiness of your life depends upon the quality of your thoughts.", "author": "Marcus Aurelius" },
  { "id": 5, "quote": "If it is not right, do not do it; if it is not true, do not say it.", "author": "Marcus Aurelius" },
  { "id": 6, "quote": "No man is free who is not master of himself.", "author": "Epictetus" },
  { "id": 7, "quote": "Luck is what happens when preparation meets opportunity.", "author": "Seneca" },
  { "id": 8, "quote": "Difficulties strengthen the mind, as labor does the body.", "author": "Seneca" },
  { "id": 9, "quote": "Waste no more time arguing about what a good man should be. Be one.", "author": "Marcus Aurelius" },
  { "id": 10, "quote": "He who fears death will never do anything worthy of a living man.", "author": "Seneca" },
  { "id": 11, "quote": "First say to yourself what you would be; and then do what you have to do.", "author": "Epictetus" },
  { "id": 12, "quote": "The best revenge is to be unlike him who performed the injury.", "author": "Marcus Aurelius" },
  { "id": 13, "quote": "Wealth consists not in having great possessions, but in having few wants.", "author": "Epictetus" },
  { "id": 14, "quote": "Begin at once to live, and count each separate day as a separate life.", "author": "Seneca" },
  { "id": 15, "quote": "If you are distressed by anything external, the pain is not due to the thing itself.", "author": "Marcus Aurelius" },
  { "id": 16, "quote": "Freedom is the only worthy goal in life.", "author": "Epictetus" },
  { "id": 17, "quote": "A gem cannot be polished without friction, nor a man perfected without trials.", "author": "Seneca" },
  { "id": 18, "quote": "Look within. Within is the fountain of good.", "author": "Marcus Aurelius" },
  { "id": 19, "quote": "Don’t explain your philosophy. Embody it.", "author": "Epictetus" },
  { "id": 20, "quote": "It is the power of the mind to be unconquerable.", "author": "Seneca" },

  { "id": 21, "quote": "How long are you going to wait before you demand the best for yourself?", "author": "Epictetus" },
  { "id": 22, "quote": "Accept the things to which fate binds you.", "author": "Marcus Aurelius" },
  { "id": 23, "quote": "Life is very short and anxious for those who forget the past.", "author": "Seneca" },
  { "id": 24, "quote": "Man is disturbed not by things, but by views of things.", "author": "Epictetus" },
  { "id": 25, "quote": "The soul becomes dyed with the color of its thoughts.", "author": "Marcus Aurelius" },
  { "id": 26, "quote": "He suffers more than necessary who suffers before it is necessary.", "author": "Seneca" },
  { "id": 27, "quote": "If you want to improve, be content to be thought foolish.", "author": "Epictetus" },
  { "id": 28, "quote": "Very little is needed to make a happy life.", "author": "Marcus Aurelius" },
  { "id": 29, "quote": "As is a tale, so is life: not how long it is, but how good it is.", "author": "Seneca" },
  { "id": 30, "quote": "Make the best use of what is in your power.", "author": "Epictetus" },

  { "id": 31, "quote": "Everything we hear is an opinion, not a fact.", "author": "Marcus Aurelius" },
  { "id": 32, "quote": "Sometimes even to live is an act of courage.", "author": "Seneca" },
  { "id": 33, "quote": "Do not seek for events to happen as you wish.", "author": "Epictetus" },
  { "id": 34, "quote": "Loss is nothing else but change.", "author": "Marcus Aurelius" },
  { "id": 35, "quote": "Hang on to your youthful enthusiasms.", "author": "Seneca" },
  { "id": 36, "quote": "Only the educated are free.", "author": "Epictetus" },
  { "id": 37, "quote": "The impediment to action advances action.", "author": "Marcus Aurelius" },
  { "id": 38, "quote": "True happiness is to enjoy the present.", "author": "Seneca" },
  { "id": 39, "quote": "No great thing is created suddenly.", "author": "Epictetus" },
  { "id": 40, "quote": "The universe is change; our life is what our thoughts make it.", "author": "Marcus Aurelius" },

  { "id": 41, "quote": "Difficulties strengthen the spirit.", "author": "Seneca" },
  { "id": 42, "quote": "Seek not the good in external things.", "author": "Epictetus" },
  { "id": 43, "quote": "What we do now echoes in eternity.", "author": "Marcus Aurelius" },
  { "id": 44, "quote": "He who is brave is free.", "author": "Seneca" },
  { "id": 45, "quote": "Circumstances do not make the man.", "author": "Epictetus" },
  { "id": 46, "quote": "Be tolerant with others and strict with yourself.", "author": "Marcus Aurelius" },
  { "id": 47, "quote": "While we wait for life, life passes.", "author": "Seneca" },
  { "id": 48, "quote": "We have two ears and one mouth.", "author": "Epictetus" },
  { "id": 49, "quote": "Choose not to be harmed — and you won’t feel harmed.", "author": "Marcus Aurelius" },
  { "id": 50, "quote": "Life is like a play; it’s the performance that counts.", "author": "Seneca" },

  { "id": 51, "quote": "Do every act of your life as though it were the last.", "author": "Marcus Aurelius" },
  { "id": 52, "quote": "The greater the difficulty, the more glory.", "author": "Epictetus" },
  { "id": 53, "quote": "Time heals what reason cannot.", "author": "Seneca" },
  { "id": 54, "quote": "What stands in the way becomes the way.", "author": "Marcus Aurelius" },
  { "id": 55, "quote": "We are more often frightened than hurt.", "author": "Seneca" },
  { "id": 56, "quote": "Practice yourself in little things.", "author": "Epictetus" },
  { "id": 57, "quote": "Everything is ephemeral.", "author": "Marcus Aurelius" },
  { "id": 58, "quote": "It is quality rather than quantity that matters.", "author": "Seneca" },
  { "id": 59, "quote": "If you wish to be rich, do not add to your money.", "author": "Seneca" },
  { "id": 60, "quote": "Freedom is secured by self-control.", "author": "Epictetus" },

  { "id": 61, "quote": "A man’s worth is no greater than his ambitions.", "author": "Marcus Aurelius" },
  { "id": 62, "quote": "He who has anticipated trouble takes away its power.", "author": "Seneca" },
  { "id": 63, "quote": "Don’t hope events will turn out the way you want.", "author": "Epictetus" },
  { "id": 64, "quote": "The mind adapts and converts to its own purposes.", "author": "Marcus Aurelius" },
  { "id": 65, "quote": "There is no easy way from the earth to the stars.", "author": "Seneca" },
  { "id": 66, "quote": "If it is endurable, then endure it.", "author": "Marcus Aurelius" },
  { "id": 67, "quote": "We learn not in school but in life.", "author": "Seneca" },
  { "id": 68, "quote": "Small things are small only to the small-minded.", "author": "Epictetus" },
  { "id": 69, "quote": "The art of living is more like wrestling.", "author": "Marcus Aurelius" },
  { "id": 70, "quote": "It is not the man who has too little, but too much.", "author": "Seneca" },

  { "id": 71, "quote": "Do not waste time on what you cannot change.", "author": "Marcus Aurelius" },
  { "id": 72, "quote": "The wise man is content with his lot.", "author": "Seneca" },
  { "id": 73, "quote": "If you want to conquer fear, do not sit home.", "author": "Epictetus" },
  { "id": 74, "quote": "The happiness of your life depends on your thoughts.", "author": "Marcus Aurelius" },
  { "id": 75, "quote": "To bear trials with a calm mind robs misfortune of its strength.", "author": "Seneca" },
  { "id": 76, "quote": "Nothing great is produced suddenly.", "author": "Epictetus" },
  { "id": 77, "quote": "Live a good life.", "author": "Marcus Aurelius" },
  { "id": 78, "quote": "It is better to conquer grief than to deceive it.", "author": "Seneca" },
  { "id": 79, "quote": "Attach yourself to what is spiritually superior.", "author": "Epictetus" },
  { "id": 80, "quote": "All is ephemeral.", "author": "Marcus Aurelius" },

  { "id": 81, "quote": "As long as you live, keep learning.", "author": "Seneca" },
  { "id": 82, "quote": "The price of freedom is discipline.", "author": "Epictetus" },
  { "id": 83, "quote": "Today I escaped anxiety.", "author": "Marcus Aurelius" },
  { "id": 84, "quote": "Life without purpose is drifting.", "author": "Seneca" },
  { "id": 85, "quote": "First learn the meaning of what you say.", "author": "Epictetus" },
  { "id": 86, "quote": "Be like the rocky headland.", "author": "Marcus Aurelius" },
  { "id": 87, "quote": "We live as if destined to live forever.", "author": "Seneca" },
  { "id": 88, "quote": "The key is to keep company only with people who uplift you.", "author": "Epictetus" },
  { "id": 89, "quote": "Soon you will have forgotten everything.", "author": "Marcus Aurelius" },
  { "id": 90, "quote": "Difficulties are meant to rouse.", "author": "Seneca" },

  { "id": 91, "quote": "No man is crushed by misfortune unless he has first been deceived.", "author": "Seneca" },
  { "id": 92, "quote": "Make use of what is in your power.", "author": "Epictetus" },
  { "id": 93, "quote": "Do not act as if you were going to live ten thousand years.", "author": "Marcus Aurelius" },
  { "id": 94, "quote": "He who indulges in empty fears earns real fears.", "author": "Seneca" },
  { "id": 95, "quote": "It is impossible to learn what you think you already know.", "author": "Epictetus" },
  { "id": 96, "quote": "The best answer to anger is silence.", "author": "Marcus Aurelius" },
  { "id": 97, "quote": "A man who suffers before it is necessary suffers more than necessary.", "author": "Seneca" },
  { "id": 98, "quote": "Don’t seek that events happen as you wish.", "author": "Epictetus" },
  { "id": 99, "quote": "Be content to seem what you really are.", "author": "Marcus Aurelius" },
  { "id": 100, "quote": "Life’s like a play — what matters is how well you act.", "author": "Seneca" }
]
